### ISSUE TITLE
Can you add forward and back buttons?

### ISSUE THREAD

**Issue by tyeeman** [Alanaktion/Gallery#1]
It would be appreciated! Nice gallery!

**Comment by Alanaktion** [comment]
Currently this gallery works by directly linking to image files themselves so it's not able to handle navigation apart from showing breadcrumbs for subdirectories. I have a much more feature-heavy [Gallery2](https://github.com/Alanaktion/Gallery2) project that's mostly unmaintained but if navigating between images directly is useful it'd be more likely to be implemented there.

Of course you're welcome to fork this project and implement whatever features you'd like, but I don't plan to support anything myself here that wouldn't be possible by just linking directly to image files.
